=== zjlyy-oss/xmb/xml/note.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT note (xy)>
<!ELEMENT xy (to,from,heading,body,lastname,xinzhi,wang,phone)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT xinzhi (#PCDATA)>
<!ELEMENT wang (#PCDATA)>
<!ELEMENT phone (#PCDATA)>

=== zjlyy-oss/xmb/xml/note.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="note.css" type="text/css"?>
<!DOCTYPE note SYSTEM "note.dtd">
<note>
<xy>
<to>兰博基尼汽车公司</to>
<from>Automobili Lamborghini S.p.A.</from>
<heading>意大利圣亚加塔·波隆尼</heading>
<body>1963年</body>
<lastname>跑车</lastname>
<xinzhi>外商独资，归属奥迪汽车/大众集团</xinzhi>
<wang>www.lamborghini.com</wang>
<phone>400-116-6606</phone>
</xy>
</note>
